### ISSUE TITLE
Cannot login with Google+ when running the app locally with Docker

### ISSUE THREAD

**Issue by maityneil001** [mmumshad/ansible-playable#1]
Steps to reproduce:

1. Start Docker
2. run the command `docker run -p 8080:8080 mmumshad/ansible-playable`
3. Open localhost:8080/login
4. click Google+ button

NOTE: I am binding port 8080 as port 80 is already in use in my case.

I have attached an image.
![screen shot 2017-07-18 at 12 22 48 pm](https://user-images.githubusercontent.com/10528652/28304189-2b4d6ce4-6bb4-11e7-887e-4381bb8e2967.png)

**Comment by mmumshad** [comment]
Hi, for this to work, you will need to set two additional environment variables while running docker container. Check instructions in the Readme page here: https://github.com/mmumshad/ansible-playable#authentication

And, of course, you will need to configure Google Authentication in google developer console to get the keys.
