### ISSUE TITLE
ansible-playable.com returns error code 503

### ISSUE THREAD

**Issue by amitmindstix** [mmumshad/ansible-playable#17]
Is the demo site down?
I tried building from source and run locally but facing issues in creating roles - wondering if it is possible to bring up the demo site so that I can try it online

**Comment by mmumshad** [comment]
Hi,  it should be up by now.

**Comment by greggworldwide** [comment]
Still down for me...   #24

**Comment by mmumshad** [comment]
Hey, it should be up now.

**Comment by greggworldwide** [comment]
Thanks.  It is all good now!  You Rock!  I will get to work checking it out.  Thanks again!!
