### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by vindberg** [mmumshad/ansible-playable#36]
I see great potential for this project, but development seem to have stopped some 2 years ago. Any news on this @mmumshad ?

**Comment by sabueso** [comment]
Seems that, yes...

**Comment by mmumshad** [comment]
Hey guys! Yeah it is kind of dead. I built it to speed up things for a project. But since that was finished, I haven't been able to continue developing it. Right now it's kind of outdated. Sorry!

**Comment by vindberg** [comment]
Do you know of any good alternatives? (Something that is not Ansible Tower at 13.000/USD/Year). :)

**Comment by sabueso** [comment]
@vindberg you can use AWX FOSS edition ;)

**Comment by vindberg** [comment]
@sabueso Thanks, looking into that now.
